### ISSUE TITLE
Sync version

### ISSUE THREAD

**Issue by TheGejr** [IonicaBizau/node-cli-frames#20]
Is it possible to make sync a possibility?

**Comment by IonicaBizau** [comment]
How would you imagine the sync version would work?

**Comment by TheGejr** [comment]
I think the best solution would be something like:
```js
new CliFrames({
    frames: frames,
    async: false,  // It should most likely be async as default, so to play it sync you must specify it to be false
    autostart: {
      delay: 500
    }
  });
```

**Comment by IonicaBizau** [comment]
But that will be still async (the delay will be a `setTimeout` call perhaps).

**Comment by IonicaBizau** [comment]
But that will be still async (the delay will be a `setTimeout` call perhaps).
